### ISSUE TITLE
Lookup not working

### ISSUE THREAD

**Issue by ACasset** [Torie-Coding/keepass#32]
Hello,

First of all, thanks for your work!

I've been trying to use your collection, and I've partly succeeded : the modules to create entries work great, but the lookup does not.

My playbook:
```yml
- hosts: localhost
  tasks:
    - name: Create a new group in KeePass
      torie_coding.keepass.group:
        action: create
        database: "{{ keepass_database }}"
        database_password: "{{ keepass_password }}"
        name: MyNewGroup
        notes: This is a new group created by Ansible.
        create_path: true
      register: group

    - name: Create a new entry in KeePass
      torie_coding.keepass.entry:
        action: create
        database: "{{ keepass_database }}"
        database_password: "{{ keepass_password }}"
        title: MyNewEntry
        username: myusername
        password: mypassword
        url: https://example.com
        notes: This is a new entry created by Ansible.
        group_path: MyNewGroup
        icon_id: 48
      register: entry

    - name: Display test entry
      ansible.builtin.debug:
        var: entry

    - name: Find test entry through group and title
      debug:
        msg: "{{ lookup('torie_coding.keepass.lookup', 'entry', database=keepass_database, database_password=keepass_password, group_path='MyNewGroup/', title='MyNewEntry') }}"

    - name: Find test entry through title
      debug:
        msg: "{{ lookup('torie_coding.keepass.lookup', 'entry', database=keepass_database, database_password=keepass_password, title='MyNewEntry') }}"

    - name: Find test entry through group
      debug:
        msg: "{{ lookup('torie_coding.keepass.lookup', 'entry', database=keepass_database, database_password=keepass_password, group_path='MyNewGroup/') }}"

    # I've added manually some tags in the meantime
    - name: Find test entry through tags
      ansible.builtin.debug:
        msg: "{{ lookup('torie_coding.keepass.lookup', 'entry', database=keepass_database, database_password=keepass_password, tags=['dummy']) }}"
```
The output
```bash
PLAY [localhost] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [Create a new group in KeePass] ***********************************************************************************
ok: [localhost]

TASK [Create a new entry in KeePass] ***********************************************************************************
ok: [localhost]

TASK [Display test entry] **********************************************************************************************
ok: [localhost] => {
    "entry": {
        "changed": false,
        "failed": false,
        "group_path": "MyNewGroup/",
        "icon_id": "48",
        "notes": "This is a new entry created by Ansible.",
        "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
        "title": "MyNewEntry",
        "url": "https://example.com",
        "username": "myusername"
    }
}

TASK [Find test entry through group and title] *************************************************************************
ok: [localhost] => {
    "msg": []
}

TASK [Find test entry through title] ***********************************************************************************
ok: [localhost] => {
    "msg": []
}

TASK [Find test entry through group] ***********************************************************************************
ok: [localhost] => {
    "msg": []
}

TASK [Find test entry through tags] ************************************************************************************
ok: [localhost] => {
    "msg": []
}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

The entries are correctly created in my KeePass (I can see it happening in real time), but I cannot figure out why the lookup returns nothing.

I'm using all the latest versions : ansible core 2.17.3, torie_coding.keepass 1.2.2, pykeepass 4.0.3

The weird part : the viczem.keepass lookup does find the entries.

Is there something I can test that would help you find the root cause ?
