### ISSUE TITLE
Nested group structure support

### ISSUE THREAD

**Issue by vykhx** [Torie-Coding/keepass#5]
Thank you for the implementation of this module, it works great! 

A couple additional feature that would be nice to have is to have:
- the ability to recursively create nested groups through the create action, for example by specifying path
- the ability to automatically create a nested group structure when creating an entry

I think we can expand the logic a bit at this point:
https://github.com/Torie-Coding/keepass/blob/5d01b09941bd425991b3bfa2082239a9833ce45a/plugins/modules/group.py#L205-L221

to one of the solution options:
```python
from pykeepass import PyKeePass

kp = PyKeePass(...)

group_name = "Group 3"
group_path = "Group 1/Group 2"

group_names = group_path.split("/")
group_names.append(group_name)

group = kp.find_groups(path=group_names)
if not group:
    for idx, name in enumerate(group_names):
        path = group_names[0 : idx + 1]

        under_group = kp.find_groups(path=path)
        if not under_group:
            dest_group = kp.find_groups(path=path[:-1]) if len(path) > 1 else kp.root_group
            if not dest_group:
                raise Exception("No destination group found")

            group = kp.add_group(dest_group, group_name=name)

    kp.save()

print(group)
```

**Comment by Torie-Coding** [comment]
Hi vykhx,

we've updated our code, thank you for your code snippet, it was really helpfull. 
You can now create nested groups.
Please be aware of the changes we've made regarding to some input parameters and output values returned by both the group an the entry module.
You can find find further information in the Changelog and the documentation.

Referring to your second request, creating nested groups or creating a group when an entry is created, we are sorry to tell you, this will not be implemented. This leads back to the separation between group actions and entry actions we have chosen.
By realizing your request we would mix both actions, which can create some mess in the future. The mixture should be done on Ansible level not inside of the python modules. We hope you can understand this.

To hopefully satisfy your request even though we didn't change our modules, we've put down a solution in Ansible, that we would recommend (this snippet also contains the example to create a nested group):
```
   - name: Create nested Group.
      torie_coding.keepass.group:
        action: create
        database: database_path
        database_password: your_password
        name: my_group
        create_path: true
        path: foo/bar
      register: nested_group

    - name: Add entry to specific directory.
      torie_coding.keepass.entry:
        action: create
        database: database_path
        database_password: your_password
        title: my_title
        username: my_username
        group_path: "{{ nested_group.full_path }}"
      register: result_entry

    - name: Show result.
      ansible.builtin.debug:
        var: result_entry
```
